language: node_js
node_js: stable
before_script:
  - yarn boot
branches:
  only:
    - master
    - develop
    - v2
    - /^greenkeeper-.*$/
cache:
  yarn: true
  directories:
    - node_modules
    - packages/react-instantsearch/node_modules
    - packages/react-instantsearch-theme-algolia/node_modules
